import { ICIOfPolicyDetail, IListMetricsPolicyVersion, IMonitoringPolicyVersions, ITipoCambio, IUpdateListaPolitica, TIPOCAMBIO } from "../../../Types"

export const initialFrontMetricToCreate = (selectedRow: ICIOfPolicyDetail, metric: IUpdateListaPolitica, ID: string): (IListMetricsPolicyVersion & { ID: string } & ITipoCambio) => {
  return {
    ID: ID,
    tipo_cambio: TIPOCAMBIO.NUEVO,
    ALERTA: "",
    CLASE: selectedRow.CLASE,
    CLIENTES: "",
    COMMAND_PROCESS: metric.command_process,
    COMMAND_PATH: metric.command_path,
    CRITICAL: {
      ID_DETALLE_POLITICA: 0,
      VALOR: "Por Definir",
      NRO_POOLEO: "Por Definir"
    },
    DATA_D: "",
    DESCRIPCION: "",
    DETALLE: "",
    EQUIPO_ESTADO: selectedRow.EQUIPO_ESTADO,
    ESCALAMIENTO: "",
    ESTADO: 0,
    FAMILIA: selectedRow.FAMILIA,
    FATAL: {
      ID_DETALLE_POLITICA: 0,
      VALOR: "Por Definir",
      NRO_POOLEO: "Por Definir"
    },
    FECHA_CREACION: "",
    FECHA_MODIFICACION: "",
    FRECUENCIA: "Por Definir",
    HERRAMIENTA_MONITOREO: "Por Definir",
    ID_DETALLE_VERSION: 0,
    ID_EQUIPO: 0,
    UNIDADES: "",
    ID_VERSION: 0,
    INTERFACE: "",
    IP: selectedRow.IP,
    METRICAS: metric.metricas,
    METRICA_RUTA: metric.metrica_ruta,
    MONITOREADO_DESDE: "",
    NOMBRE: selectedRow.NOMBRE,
    NOMBRE_CI: selectedRow.NOMBRE_CI,
    NOMBRE_MODULO: "",
    NRO_POOLEOS: "Por Definir",
    OBSERVACION: "",
    PATH_D: "",
    PROTOCOLO: metric.protocolo,
    PUERTO: metric.puerto,
    RECURSOS: "",
    SERVICIO_ASOCIADO: metric.servicio_asociado,
    TIPO_EQUIPO: "Por Definir",
    TIPO_MONITOREO: "",
    UMBRAL_CRITICAL: "",
    UMBRAL_WARNING: "",
    USUARIO_CREACION: "",
    USUARIO_MODIFICACION: "",
    TABLESPACE_NAME: metric.tablespace_name,
    NOMBRE_INSTANCIA: metric.nombre_instancia,
    NRO_PUERTO_INSTANCIA: metric.nro_puerto_instancia,
    NOMBRE_DB: metric.nombre_db,
    NOMBRE_JOB: metric.nombre_job,
    DISPONIBILIDAD_PROCESO: metric.disponibilidad_proceso,
    NOMBRE_INTERFAZ: metric.nombre_interfaz,
    ESTADO_INTERFACE: metric.estado_interface,
    ALL_REPLICAS: metric.all_replicas,
    PRIMARY_REPLICAS: metric.primary_replicas,
    SOME_REPLICAS: metric.some_replicas,
    APP_POOL: metric.app_pool,
    NAME_WEB: metric.name_web,
    WARNING: {
      ID_DETALLE_POLITICA: ID,
      VALOR: "Por Definir",
      NRO_POOLEO: "Por Definir"
    }
  }
}

export const initialGenericMetricToCreate = (row: ICIOfPolicyDetail, modalInfo: IMonitoringPolicyVersions, metricaName: string): IUpdateListaPolitica => ({
  id_detalle_politica: 0,
  id_politica: modalInfo.ID_POLITICA,
  nro_version: modalInfo.NRO_VERSION,
  id_equipo: row.ID_EQUIPO,
  estado: 1,
  metricas: metricaName,
  tipo_equipo: "",
  herramienta_monitoreo: "",
  umbral: "",
  nro_pooleos: "",
  frecuencia: "",
  metrica_ruta: "",
  servicio_asociado: "",
  command_process: "",
  command_path: "",
  protocolo: "",
  puerto: "",
  observacion: "",
  tipo_monitoreo: "",
  monitoreado_desde: "",
  nombre_instancia: "",
  nro_puerto_instancia: "",
  tablespace_name: "",
  nombre_db: "",
  nombre_job: "",
  disponibilidad_proceso: "",
  nombre_interfaz: "",
  estado_interface: "",
  all_replicas: "",
  primary_replicas: "",
  some_replicas: "",
  app_pool: "",
  name_web: ""
})

