import { IMotivoSalto, IAssignServerToGroup, IBodyAssignCredential, IBodyListPlanification, IBodyServersCredential, ICreateConfiguration, ICreateCredential, ICreateGroup, ICreatePlanification, ICreateTemplate, IInitSearchHistoricPatches, IInitSearchPendingPatches, IReassignTemplateOfGroup, IUpdateConfiguration, IUpdateCredential, IUpdateGroup, IUpdateGroupName, IUpdateTemplate, IUpdateIP, ICreateConfigurationLinux, IUpdateConfigurationLinux, ISearchLinuxConfiguration, IExecuteTemplateLinux, ISearchFilter } from '../views/automation/Types'
import { OPERATE_SYSTEMS } from '../views/automation/Types'
import { ApiManagementCCS } from './ApiV2'

const AutomationService = {
   createGroup: (newGroup: ICreateGroup) => ApiManagementCCS.post("/parchado/crear_grupo", newGroup).then((data) => data),
   assignServerToGroup: (serversData: IAssignServerToGroup) => ApiManagementCCS.post("/parchado/crear_grupo_servidor/", serversData).then((data) => data),
   getServersByClientProject: (nameClient: string, idProject: string) => ApiManagementCCS.get(`/parchado/listar_servidor_grupos/${nameClient}/${idProject}`).then((data) => data),
   updateGroup: (groupUpdated: IUpdateGroup) => ApiManagementCCS.post("/parchado/actualizar_grupo/", groupUpdated).then((data) => data),
   updateTemplate: (templateUpdated: IUpdateTemplate) => ApiManagementCCS.post("/parchado/actualizar_plantilla/", templateUpdated).then((data) => data),
   createTemplate: (newTemplate: ICreateTemplate) => ApiManagementCCS.post("/parchado/crear_plantilla/", newTemplate).then((data) => data),
   getListTemplate: (so: OPERATE_SYSTEMS) => ApiManagementCCS.get(`/parchado/listar_plantilla_so/${so}`).then((data) => data),
   getListAWXRoutines: (isLinux: string) => ApiManagementCCS.get(`/parchado/listar_rutinarias_awx/${isLinux}`).then((data) => data),
   getListAWXRoutinesOfTemplate: (idTemplate: string) => ApiManagementCCS.get(`/parchado/listar_rutinaria_by_plantilla/${idTemplate}`).then((data) => data),
   getListGroup: (so: OPERATE_SYSTEMS) => ApiManagementCCS.get(`/parchado/listar_grupo/${so}`).then((data) => data),
   getGroupsServersPatches: (nameClient: string, idProject: string) => ApiManagementCCS.get(`/parchado/obtener_grupos_servidor_parche/${nameClient}/${idProject}`).then((data) => data),
   getGroupsServersLinux: (nameClient: string, idProject: string) => ApiManagementCCS.get(`/parchado/obtener_grupos_servidor_parche_linux/${nameClient}/${idProject}/`).then((data) => data),
   deleteServerInGroup: (idGroup: string, idServer: string) => ApiManagementCCS.post(`/parchado/eliminar_grupo_servidor/${idGroup}/${idServer}`).then((data) => data),
   getServerInformation: (idServer: string) => ApiManagementCCS.get(`/parchado/obtener_informacion_equipo/${idServer}`).then((data) => data),
   getServersAssigned: (nameClient: string, idProject: string) => ApiManagementCCS.get(`/parchado/listar_servidor_asignado/${nameClient}/${idProject}`).then((data) => data),
   getListHistoricPatches: (idServer: string) => ApiManagementCCS.get(`/parchado/listar_parches_historicos/${idServer}`).then((data) => data),
   getListExecutions: (nameClient: string, idProject: string) => ApiManagementCCS.get(`/parchado/listar_ejecuciones/${nameClient}/${idProject}`).then((data) => data),
   getExecutiondetail: (idExecution: string) => ApiManagementCCS.get(`/parchado/listar_ejecuciones_detalle/${idExecution}`).then((data) => data),
   createCredential: (credential: ICreateCredential) => ApiManagementCCS.post(`/parchado/crear_credencial/`, credential).then((data) => data),
   updateCredential: (updatedCredential: IUpdateCredential) => ApiManagementCCS.put(`/parchado/actualizar_credencial/`, updatedCredential).then((data) => data),
   getListCredentials: () => ApiManagementCCS.get(`/parchado/listar_credencial/`).then((data) => data),
   deleteCredential: (id_credential: string) => ApiManagementCCS.delete(`/parchado/eliminar_credencial/${id_credential}`).then((data) => data),
   createConfiguration: (configuration: ICreateConfiguration) => ApiManagementCCS.post(`/parchado/crear_programacion_ejecucion/`, configuration).then((data) => data),
   getConfigurationOfExecution: (idExecution: string) => ApiManagementCCS.get(`/parchado/obtener_ejecucion_grupos_servidor_parche/${idExecution}`).then((data) => data),
   updateConfiguration: (id_ejecucion: string, configuration: IUpdateConfiguration) => ApiManagementCCS.post(`/parchado/actualizar_programacion_ejecucion/${id_ejecucion}`, configuration).then((data) => data),
   getListServersWithORWithoutCredential: (whoServerWants: IBodyServersCredential) => ApiManagementCCS.post(`/parchado/listar_credencial_servidor/`, whoServerWants).then((data) => data),
   assignServerToCredential: (serversToAssign: IBodyAssignCredential) => ApiManagementCCS.post(`/parchado/asignar_credencial/`, serversToAssign).then((data) => data),
   deleteCredentialOfServer: (id_credential: string, id_server: string) => ApiManagementCCS.delete(`/parchado/eliminar_credencial_equipo/${id_credential}/${id_server}`).then((data) => data),
   save_planification: (planification: ICreatePlanification[]) => ApiManagementCCS.post(`/parchado/guardar_planificacion/`, planification).then((data) => data),
   deletePlanification: (idPlanification: string) => ApiManagementCCS.delete(`/parchado/eliminar_planificacion/${idPlanification}`).then((data) => data),
   getListPlanification: (whoPlanificationWants: IBodyListPlanification) => ApiManagementCCS.post(`/parchado/listar_planificacion/`, whoPlanificationWants).then((data) => data),
   initSearchHistoricPatches: (serversToFind: IInitSearchHistoricPatches) => ApiManagementCCS.patch(`/parchado/actualizar_historial_parches/`, serversToFind).then((data) => data),
   initSearchPendingPatches: (serversToFind: IInitSearchPendingPatches) => ApiManagementCCS.patch(`/parchado/ejecutar_busqueda_parches`, serversToFind).then((data) => data),
   initPatching: (serversToExec: IInitSearchPendingPatches, idExecution: string) => ApiManagementCCS.patch(`/parchado/ejecutar_parchado_awx/${idExecution}`, serversToExec).then((data) => data),
   listProgressExecution: (idExecution: string) => ApiManagementCCS.get(`/parchado/listar_ejecucion_progreso/${idExecution}`).then((data) => data),
   deleteExecution: (idExecution: string) => ApiManagementCCS.delete(`/parchado/eliminar_ejecucion_window/${idExecution}`).then((data) => data),
   getTemplateOfGroup: (idGroup: string) => ApiManagementCCS.get(`/parchado/obtener_plantilla_by_grupo/${idGroup}`).then((data) => data),
   reassignTemplate: (groupToChange: IReassignTemplateOfGroup) => ApiManagementCCS.post(`/parchado/cambiar_grupo_plantilla/`, groupToChange).then((data) => data),
   changeGroupName: (idGroup: string, newGroupName: IUpdateGroupName) => ApiManagementCCS.post(`/parchado/actualizar_nombre_grupo/${idGroup}`, newGroupName).then((data) => data),
   restartExecution: (idExecution: string, idDetailExecution: string, user: string, idServer: string) => ApiManagementCCS.patch(`/parchado/ejecutar_relanzar_rutinaria_awx/${idExecution}/${idDetailExecution}/${user}/${idServer}`,).then((data) => data),
   deleteTemplate: (idTemplate: string) => ApiManagementCCS.post(`/parchado/eliminar_plantilla/${idTemplate}`,).then((data) => data),
   cancelExecution: (idExecution: string, idDetailExecution: string, user: string, idServer: string) => ApiManagementCCS.patch(`/parchado/ejecutar_cancelar_rutinaria_awx/${idExecution}/${idDetailExecution}/${user}/${idServer}`,).then((data) => data),
   getLogsJobAwx: (id_job_awx: string) => ApiManagementCCS.get(`/parchado/ver_respuesta_rutinaria_awx/${id_job_awx}`,).then((data) => data),
   saltarExecution: (idExecution: string, idDetailExecution: string, user: string, idServer: string, motivo: IMotivoSalto) => ApiManagementCCS.patch(`/parchado/ejecutar_saltar_rutinaria_awx/${idExecution}/${idDetailExecution}/${user}/${idServer}`, motivo).then((data) => data),
   getDifferencesPrePost: (idExecution: string, idServer: string) => ApiManagementCCS.get(`/parchado/diferencia_archivo_checklist/${idExecution}/${idServer}`).then((data) => data),
   getCheckList: (idExecution: string, idServer: string) => ApiManagementCCS.get(`/parchado/ver_checklist/${idExecution}/${idServer}`).then((data) => data),
   updateIP: (newIP: IUpdateIP) => ApiManagementCCS.put(`/parchado/actualizar_grupo_servidor/`, newIP).then((data) => data),
   getServersAssignedLinux: (nameClient: string, idProject: string) => ApiManagementCCS.get(`/parchado/listar_servidor_asignado_linux/${nameClient}/${idProject}`).then((data) => data),
   getServerInformationLinux: (idServer: string) => ApiManagementCCS.get(`/parchado/obtener_informacion_equipo_linux/${idServer}`).then((data) => data),
   getDataFromMonitorOptions: (params: { tabla: string, filtro: string }) => ApiManagementCCS.post("/administracion/opcion/listar", params).then((data) => data),
   createConfigurationLinux: (configuration: ICreateConfigurationLinux) => ApiManagementCCS.post(`/parchado/crear_programacion_ejecucion_linux/`, configuration).then((data) => data),
   getListExecutionsLinux: (nameClient: string, idProject: string) => ApiManagementCCS.get(`/parchado/listar_ejecuciones_linux/${nameClient}/${idProject}`).then((data) => data),
   getExecutiondetailLinux: (idExecution: string) => ApiManagementCCS.get(`/parchado/listar_ejecuciones_detalle_linux/${idExecution}`).then((data) => data),
   updateConfigurationLinux: (id_ejecucion: string, configuration: IUpdateConfigurationLinux) => ApiManagementCCS.post(`/parchado/actualizar_programacion_ejecucion_linux/${id_ejecucion}`, configuration).then((data) => data),
   getConfigurationLinuxOfExecution: (idExecution: string) => ApiManagementCCS.get(`/parchado/obtener_ejecucion_grupos_servidor_parche_linux/${idExecution}`).then((data) => data),
   listProgressLinuxExecution: (idExecution: string) => ApiManagementCCS.get(`/parchado/listar_ejecucion_progreso_linux/${idExecution}`).then((data) => data),
   deleteExecutionLinux: (idExecution: string) => ApiManagementCCS.delete(`/parchado/eliminar_ejecucion_linux/${idExecution}`).then((data) => data),
   getExecutionHistoryByServer: (idServer: string) => ApiManagementCCS.get(`/parchado/listar_historial_ejecucion_por_equipo_linux/${idServer}`).then((data) => data),
   executeSearchLinux: (serversToFind: ISearchLinuxConfiguration) => ApiManagementCCS.patch(`/parchado/ejecutar_busqueda_parches_linux`, serversToFind).then((data) => data),
   createCredentialLinux: (credential: ICreateCredential) => ApiManagementCCS.post(`/parchado/crear_credencial_v2/`, credential).then((data) => data),
   startExecutionLinux: (configuration: IExecuteTemplateLinux, idExecution: string) => ApiManagementCCS.patch(`/parchado/ejecutar_parchado_awx_linux/${idExecution}`, configuration).then((data) => data),
   deleteServerInGroupLinux: (idGroup: string, idServer: string) => ApiManagementCCS.post(`/parchado/eliminar_grupo_servidor_linux/${idGroup}/${idServer}`).then((data) => data),
   getPhotoPrePostByServerLinux: (nroTicket: string, idServer: string) => ApiManagementCCS.get(`/parchado/listar_pre_pos_photo_linux/${nroTicket}/${idServer}`).then((data) => data),
   getDifferencesPrePostLinux: (nroTicket: string, idServer: string) => ApiManagementCCS.get(`/parchado/listar_diferencia_pre_pos_photo_linux/${nroTicket}/${idServer}`).then((data) => data),
   getLogsJobAwxLinux: (id_job_awx: string) => ApiManagementCCS.get(`/parchado/ver_respuesta_rutinaria_awx_linux/${id_job_awx}`).then((data) => data),
   getResultSearchLinux: (searchFilter: ISearchFilter) => ApiManagementCCS.post(`/parchado/listar_resultado_busqueda_linux`, searchFilter).then((data) => data),
   cancelExecutionLinux: (idExecution: string, userName: string, idServer: string) => ApiManagementCCS.patch(`/parchado/ejecutar_cancelar_rutinaria_awx_linux/${idExecution}/${userName}/${idServer}`,).then((data) => data),
   rerunExecutionLinux: (idExecution: string, userName: string, idServer: string) => ApiManagementCCS.patch(`/parchado/ejecutar_relanzar_rutinaria_awx_linux/${idExecution}/${userName}/${idServer}`,).then((data) => data),
   skipExecutionLinux: (idExecution: string, userName: string, idServer: string, motivo: IMotivoSalto) => ApiManagementCCS.patch(`/parchado/ejecutar_saltar_rutinaria_awx_linux/${idExecution}/${userName}/${idServer}`, motivo).then((data) => data),
   getTemplateByExecution: (idExecution: string) => ApiManagementCCS.get(`/parchado/listar_plantilla_by_ejecucion/${idExecution}`).then((data) => data),
   dehabilitateGroup: (idGroup: string) => ApiManagementCCS.get(`/parchado/desabilitar_grupo/${idGroup}`).then((data) => data),
}

export { AutomationService }
