import { ICreateTask, ITask } from "../components/politicas/Types";

export const initialTaskCreate: ICreateTask = {
  id_soli_tarea: 0,
  id_poli_tarea: 0,
  nombre_tarea: "",
  hora_vinicio: "",
  hora_vfin: "",
  bks_lun: 1,
  bks_mar: 1,
  bks_mie: 1,
  bks_jue: 1,
  bks_vie: 1,
  bks_sab: 0,
  bks_dom: 0,
  bks_eliminar_cont: 0,
  tipo_backup: "",
  frecuencia: "",
  contenido: "DATA",
  modo: "Full ONLine",
  herramienta: "",
  proteccion: "",
  medio: "",
  cell_manager: "SIN CELLMANAGER",
  bks_depend: "0",
  accion: "",
  aclaracion: "",
  proceso_estado: "",
  id_solicitud: 0,
  bks_tamdat: "",
  bks_detres: "",
  bks_server: "",
  tipo_tarea: "Respaldo",
  bk_lib_id: "",
  bklib_drive: "",
  detalle_dependencia: "",
  hora_estimado: "",
  minuto_estimado: "",
  bkp_tnameold: "",
  bkp_bd: "",
  comentario: "",
  estado: "1",
  usuario: "",
  lista_server: [],
  lista_ruta: [],
  lista_hora: [],
  lista_proteccion_frecuencia: []
}

export const initialTask: ITask = {
  id_soli_tarea: 0,
  id_poli_tarea: 0,
  nombre_tarea: "",
  hora_vinicio: "",
  hora_vfin: "",
  bks_lun: 1,
  bks_mar: 1,
  bks_mie: 1,
  bks_jue: 1,
  bks_vie: 1,
  bks_sab: 0,
  bks_dom: 0,
  bks_eliminar_cont: 0,
  tipo_backup: "",
  frecuencia: "Diario",
  contenido: "DATA",
  modo: "Full ONLine",
  herramienta: "",
  proteccion: "",
  medio: "",
  cell_manager: "SIN CELLMANAGER",
  bks_depend: 0,
  accion: "",
  aclaracion: "",
  proceso_estado: "",
  id_solicitud: 0,
  bks_tamdat: "",
  bks_detres: "",
  bks_server: "",
  tipo_tarea: "Respaldo",
  bk_lib_id: 0,
  bklib_drive: "",
  detalle_independencia: "",
  hora_estimado: 0,
  minuto_estimado: 0,
  bkp_tnameold: "",
  bkp_bd: "",
  comentario: "",
  estado: "0",
  aprobador: "",
  area: "",
  lista_server: [],
  lista_ruta: [],
  lista_hora: [],
  lista_proteccion_frecuencia: [],
}